#!/bin/bash

set -e

if [ ! -d out ]; then
mkdir out
fi

if [ ! -d jars ]; then
mkdir jars
fi

cd jars

if [ ! -f Saxon-HE-9.8.0-2.jar ]; then
    wget http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-2/Saxon-HE-9.8.0-2.jar
fi



